# global values passed into all helm charts by default
jx:
  # optional list of image pull secrets to use to pull container images
  imagePullSecrets: []
  # if using a non-openshift registry you can use something like this:
  #
  # imagePullSecrets:
  # - tekton-container-registry-auth
  #
  # see the example: https://github.com/jx3-gitops-repositories/jx3-kubernetes/blob/master/jx-global-values.yaml#L2-L4

  # whether to create a Release CRD when installing charts with Release CRDs included
  releaseCRD: true

  # these variables are used by 'jx gitops variables' to default environment variables
  # into the .jx/variables.sh file which can be overriden on a pre repository basis
  # or during a pipeline by writing to the '.jx/variables.sh' file
  pipelineVariables: {}
